/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IU;

import Datos.Compras;
import Datos.HashTab;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;

/**
 *
 * @author david camelo
 */
public class VentanaP extends javax.swing.JFrame {

    /**
     * Creates new form VentanaP
     */
    public VentanaP() {
        initComponents();
    }
    int id = 1;
    // Crear una tabla hash
    HashTab hashTab = new HashTab(13);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CuadroNombre = new javax.swing.JTextField();
        CuadroFecha = new javax.swing.JTextField();
        CuadroValorCuotas = new javax.swing.JTextField();
        CuadroCantidadCuotas = new javax.swing.JTextField();
        BotonAgregar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("Compras");

        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "FECHA", "VALOR DE CUOTAS", "CANTIDAD DE CUOTAS", "VALOR TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Integer.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        jScrollPane1.setViewportView(tablaCompras);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("NOMBRE");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setText("VALOR DE CUOTAS");

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setText("FECHA");

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel5.setText("CANTIDAD DE CUOTAS");

        CuadroNombre.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        CuadroFecha.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        CuadroFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadroFechaActionPerformed(evt);
            }
        });

        CuadroValorCuotas.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        CuadroValorCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadroValorCuotasActionPerformed(evt);
            }
        });

        CuadroCantidadCuotas.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        CuadroCantidadCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadroCantidadCuotasActionPerformed(evt);
            }
        });

        BotonAgregar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        BotonAgregar.setText("AGREGAR");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        botonEliminar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botonEliminar.setText("ELIMINAR");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        BotonModificar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        BotonModificar.setText("MODIFICAR");
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarActionPerformed(evt);
            }
        });

        BotonBuscar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        BotonBuscar.setText("BUSCAR");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CuadroNombre)
                    .addComponent(CuadroFecha)
                    .addComponent(CuadroValorCuotas)
                    .addComponent(CuadroCantidadCuotas)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BotonAgregar)
                        .addGap(31, 31, 31)
                        .addComponent(botonEliminar)
                        .addGap(32, 32, 32)
                        .addComponent(BotonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonBuscar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CuadroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CuadroFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CuadroValorCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(CuadroCantidadCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregar)
                    .addComponent(botonEliminar)
                    .addComponent(BotonModificar)
                    .addComponent(BotonBuscar))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CuadroValorCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadroValorCuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuadroValorCuotasActionPerformed

    private void CuadroFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadroFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuadroFechaActionPerformed

    private void CuadroCantidadCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadroCantidadCuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuadroCantidadCuotasActionPerformed

    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarActionPerformed
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaCompras.getModel();
        int seleccion = tablaCompras.getSelectedRow();
        int codigo = Integer.parseInt(tablaCompras.getValueAt(seleccion,0).toString());
        if (seleccion<0){

            JOptionPane.showMessageDialog(null,"Debe seleccionar una fila de la tabla");
        }else{
            int confirmar=JOptionPane.showConfirmDialog(null,"¿Estas seguro de Modificar este elemento?");

            if(JOptionPane.OK_OPTION==confirmar){
                modeloTabla.removeRow(seleccion);
                Compras comp1= hashTab.Seleccionar(codigo);

                hashTab.changeNombreHT(comp1,CuadroNombre.getText());
                hashTab.changeFechaHT(comp1,CuadroFecha.getText());
                hashTab.changeValorCuotaHT(comp1,Long.parseLong(CuadroValorCuotas.getText()));
                hashTab.changeNdeCuotasHT(comp1,Integer.parseInt(CuadroCantidadCuotas.getText()));
                Object [] fila = new Object[10];
                fila[0]=comp1.code;
                fila[1]=comp1.nombre;
                fila[2]=comp1.fecha;
                fila[3]=comp1.valorCuota;
                fila[4]=comp1.NdeCuotas;
                fila[5]=comp1.getTotal();
                modeloTabla.addRow(fila);
                tablaCompras.setModel(modeloTabla);
                JOptionPane.showMessageDialog(null,"Modificado correctamente");
                limpiar();


            }
        }
    }//GEN-LAST:event_BotonModificarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        String codigo = JOptionPane.showInputDialog("introduce el codigo de la compra que estas buscando");
        int compra = Integer.parseInt(codigo);

        JOptionPane.showMessageDialog(null, hashTab.BuscarHT(compra));
    }//GEN-LAST:event_BotonBuscarActionPerformed



    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:

        String nombre=CuadroNombre.getText();
        String fecha=CuadroFecha.getText();
        Long ValorDeCuotas=Long.parseLong(CuadroValorCuotas.getText());
        int CantidadDeCuotas =Integer.parseInt(CuadroCantidadCuotas.getText());
        Compras com= new Compras(nombre,fecha,ValorDeCuotas,CantidadDeCuotas,id++);
        hashTab.AgregarHT(com);
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaCompras.getModel();
        Object [] fila = new Object[10];
        fila[0]=com.code;
        fila[1]=com.nombre;
        fila[2]=com.fecha;
        fila[3]=com.valorCuota;
        fila[4]=com.NdeCuotas;
        fila[5]=com.getTotal();
        modeloTabla.addRow(fila);
        tablaCompras.setModel(modeloTabla);
        JOptionPane.showMessageDialog(null,"Agregado correctamente");
        limpiar();
    }

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaCompras.getModel();
        int selec = tablaCompras.getSelectedRow();
        int codigo = Integer.parseInt(tablaCompras.getValueAt(selec,0).toString());
        if (selec < 0){
            JOptionPane.showMessageDialog(null,"Debe seleccionar una fila de la tabla");
        }else{
            int confirmar=JOptionPane.showConfirmDialog(null,"¿Estas seguro de eleminar este elemento?");

            if(JOptionPane.OK_OPTION==confirmar){
            hashTab.EliminarHT(codigo);
            modeloTabla.removeRow(selec);
            JOptionPane.showMessageDialog(null,"Compra eliminada");

        }
        }


    }
    private void limpiar(){
        CuadroNombre.setText("");
        CuadroFecha.setText("");
        CuadroValorCuotas.setText("");
        CuadroCantidadCuotas.setText("");
    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JTextField CuadroCantidadCuotas;
    private javax.swing.JTextField CuadroFecha;
    private javax.swing.JTextField CuadroNombre;
    private javax.swing.JTextField CuadroValorCuotas;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCompras;
    // End of variables declaration//GEN-END:variables
}
